### PR TITLE
Fix types for world:get() and world:query():view()

### LINKED ISSUE #24: Single entity overload type for `World:get()` was removed

### PR DESCRIPTION
**Pull request by jackTabsCode**
This fixes a few issues:
- Being forced to wrap world:get() calls as a tuple
    - It adds back the overload.
- Not being able to use world:view()
    - Idk, the type was broken.
- The documentation for world:view()
    - It appears the writer invented a new language (JK!)

There is only one problem I've identified, and that is you must wrap single component query views as a tuple still. Can't figure out how to fix that!

Fixes #24

### CODE REVIEW

File: lib/World.d.ts [hunk 1]
```diff
@@ -236,21 +247,21 @@ type QueryResult<T extends ComponentBundle> = Query<T> & {
...
+	}
 
-	for _ in world:query(Damage):view() do end -- You can still iterate views if you want!
+	for (const [, damage] of world.query(Damage).view()) {} -- You can still iterate views if you want!
 	```
 	
 	@returns View See [View](/api/View) docs.
 	 */
-	view: View<T>;
+	view: () => View<T>;
```
Comment (Ukendio) [inline lib/World.d.ts:260]: View is already an iterable function so it should not return it.

File: lib/World.d.ts [hunk 2]
```diff
@@ -236,21 +247,21 @@ type QueryResult<T extends ComponentBundle> = Query<T> & {
...
 };
 
 type View<T extends ComponentBundle> = Query<T> & {
-	get: (this: View<T>, id: AnyEntity) => LuaTuple<T>;
+	get: (this: View<T>, id: AnyEntity) => LuaTuple<NullableArray<T>>;
```
Comment (Ukendio) [inline lib/World.d.ts]: Views provide absolute access to the query. The entity has to be present for it to return any components or else it ust returns nil. So i think it would be more accurate to say `get: (this: View<T>, id: AnyEntity) => LuaTuple<T> | undefined`

**Review by Ukendio — CHANGES_REQUESTED** [review]
Documentation looks much better and thanks for adding back the overload.

I added some comments regarding Views' types

File: lib/World.d.ts (hunk 1 above)
Comment (jackTabsCode) [reply lib/World.d.ts:260]: It does not work without it

**Review by Ukendio — APPROVED** [review]
